name: Lint

on:
  workflow_call:
    inputs:
      super-linter:
        description: Whether to run the GitHub Super-Linter
        required: false
        default: true
        type: boolean

jobs:
  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@415f4eec04da36a50da617131b6bd78f0282958b # v1.70.0
        with:
          toolchain: stable
      - run: cargo clippy

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # These vars are format strings.
          # shellcheck disable=SC2016
          go run github.com/rhysd/actionlint/cmd/actionlint@v1.6.15 \
            -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' -ignore 'SC2016:'

  super-linter:
    name: GitHub Super-Linter
    runs-on: ubuntu-latest
    # Skipped on PRs as it's quite a bit slower than the specific lints.
    if: ${{ inputs.super-linter }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
