name: Lint

on:
  workflow_call:

jobs:
  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@415f4eec04da36a50da617131b6bd78f0282958b # v1.70.0
        with:
          toolchain: stable
      - run: cargo clippy

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # These vars are format strings.
          # shellcheck disable=SC2016
          go run github.com/rhysd/actionlint/cmd/actionlint@v1.6.15 \
            -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' -ignore 'SC2016:'
