name: Prerelease

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "Version to produce"
        type: string
      release_notes:
        required: true
        description: "Release notes"
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: release-${{ inputs.version }}

jobs:
  sign:
    name: Checksum and sign
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rsign2
        uses: baptiste0928/cargo-install@v1
        with:
          crate: rsign2
          version: 0.6.1

      - name: Install b3sum
        uses: baptiste0928/cargo-install@v1
        with:
          crate: b3sum
          version: 1.3.0

      - uses: actions/download-artifact@v2
        with:
          name: builds

      - name: Checksums with BLAKE3
        run: b3sum pulumi-watch-* | tee B3SUMS

      - name: Checksums with SHA512
        run: sha512sum pulumi-watch-* | tee SHA512SUMS

      - name: Sign checksums
        shell: bash
        env:
          RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
          version: ${{ inputs.version }}
        run: |
          set -u
          echo "$RELEASE_KEY" > release.key
          set -x
          for algo in B3 SHA512; do
            echo | rsign sign \
              -p .github/workflows/release.pub \
              -s release.key \
              -t "pulumi-watch v$version signed with automated key" \
              -c 'see website for signing information' \
              -x "${algo}SUMS.auto.minisig" \
              "${algo}SUMS"
          done
          rm release.key
          cat {B3,SHA512}SUMS.auto.minisig

      - uses: actions/upload-artifact@v2
        with:
          name: builds
          retention-days: 1
          path: |
            *SUMS*

  publish:
    name: Publish
    needs: [sign]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: builds

      - uses: ncipollo/release-action@3d2de22e3d0beab188d8129c27f103d8e91bf13a
        with:
          name: v${{ inputs.version }}
          tag: release-v${{ inputs.version }}
          draft: true
          prerelease: true
          allowUpdates: true

          body: |
            PRERELEASE

            ${{ needs.info.outputs.release_notes }}

          removeArtifacts: true
          replacesArtifacts: true
          artifactErrorsFailBuild: true
          artifacts: |
            pulumi-watch-*.tar.gz
            pulumi-watch-*.zip
            *SUMS*
          # pulumi-watch-*.deb
          # pulumi-watch-*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
