name: Unit Test

on:
  workflow_call:

jobs:
  unit-test:
    name: ${{ matrix.platform }} on Rust ${{ matrix.toolchain }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: stable-ubuntu
            platform: ubuntu
            toolchain: stable
          - name: stable-windows
            platform: windows
            toolchain: stable
          - name: stable-macos
            platform: macos
            toolchain: stable
          - name: msrv-ubuntu
            platform: ubuntu
            toolchain: 1.58.0
          - name: msrv-windows
            platform: windows
            toolchain: 1.58.0
          - name: msrv-macos
            platform: macos
            toolchain: 1.58.0

    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0
      - uses: dtolnay/rust-toolchain@415f4eec04da36a50da617131b6bd78f0282958b # v1.70.0
        with:
          toolchain: stable
      - run: cargo test
