name: PR

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/ci-lint.yml

  unit-test:
    name: Unit Test
    uses: ./.github/workflows/ci-unit-test.yml

  build-ok:
    name: Build OK
    needs: [lint, unit-test]
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  test-ok:
    name: Test OK
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - run: echo OK

  publish-ok:
    name: Publish OK
    runs-on: ubuntu-latest
    steps:
      - run: echo "No-op on PRs to satisfy branch checks"
