name: Main branch

on:
  push:
    branches:
      - main
      - main-v*

concurrency: release

jobs:
  info:
    name: Gather info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Compute version
      id: version
      shell: bash
      run: |
        # Sets output VERSION
        VERSION="$(./.github/scripts/get-version)"

        ./.github/scripts/set-output version "$VERSION"
  prerelease:
    needs: [info]
    uses: ./.github/workflows/prerelease.yml
    with:
      version: ${{ fromJson(needs.info.outputs.version) }}
    secrets: inherit
