name: Release
on:
  release:
    types:
      - published

jobs:
  make-release-pr:
    name: "Make release PR"
    if: ${{ !github.event.release.prerelease && !github.event.release.draft }}
    runs-on: ubuntu-latest
    steps:
      - run: echo OK
