name: Publish Crates

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "Version to produce"
        type: string

jobs:
  cargo-publish:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --tags && git checkout tags/v${{ inputs.version }}
      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8 # v2.0.0
      - uses: dtolnay/rust-toolchain@415f4eec04da36a50da617131b6bd78f0282958b # v1.70.0
        with:
          toolchain: stable
      - run: cargo publish -p pulumi-watch --dry-run
